# 開発環境用のDockerfile
FROM node:20-alpine

# 作業ディレクトリの設定
WORKDIR /app

# 必要なパッケージのインストール
RUN apk add --no-cache python3 make g++

# パッケージマネージャーの設定
COPY package.json yarn.lock ./

# 依存関係のインストール
RUN yarn install --network-timeout 100000

# ポートの公開
EXPOSE 3000

# 開発サーバーの起動
CMD ["yarn", "dev"]
