"""Remove API key support from OAuth tokens

Revision ID: 231fcecdce3a
Revises: dee7fa186efe
Create Date: 2025-07-01 04:34:11.911707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '231fcecdce3a'
down_revision: Union[str, None] = 'dee7fa186efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop columns related to API key support
    op.drop_column('oauth_tokens', 'is_api_key', schema='team_insight')
    op.drop_column('oauth_tokens', 'backlog_space_key', schema='team_insight')
    op.drop_column('oauth_tokens', 'backlog_user_id', schema='team_insight')
    op.drop_column('oauth_tokens', 'backlog_user_email', schema='team_insight')
    op.drop_column('oauth_tokens', 'last_used_at', schema='team_insight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-add columns for API key support
    op.add_column('oauth_tokens', sa.Column('last_used_at', sa.DateTime(), nullable=True), schema='team_insight')
    op.add_column('oauth_tokens', sa.Column('backlog_user_email', sa.String(length=255), nullable=True), schema='team_insight')
    op.add_column('oauth_tokens', sa.Column('backlog_user_id', sa.String(length=100), nullable=True), schema='team_insight')
    op.add_column('oauth_tokens', sa.Column('backlog_space_key', sa.String(length=100), nullable=True), schema='team_insight')
    op.add_column('oauth_tokens', sa.Column('is_api_key', sa.Boolean(), nullable=True), schema='team_insight')
    
    # Set default value for is_api_key column
    op.execute("UPDATE team_insight.oauth_tokens SET is_api_key = false WHERE is_api_key IS NULL")
    # ### end Alembic commands ###