"""Add system_settings table

Revision ID: 5c9c05c1b476
Revises: 23220042b64e
Create Date: 2025-07-03 02:35:02.711749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9c05c1b476'
down_revision: Union[str, None] = '23220042b64e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('group', sa.String(length=100), nullable=False),
    sa.Column('value_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='team_insight'
    )
    op.create_index(op.f('ix_team_insight_system_settings_group'), 'system_settings', ['group'], unique=False, schema='team_insight')
    op.create_index(op.f('ix_team_insight_system_settings_id'), 'system_settings', ['id'], unique=False, schema='team_insight')
    op.create_index(op.f('ix_team_insight_system_settings_key'), 'system_settings', ['key'], unique=True, schema='team_insight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_insight_system_settings_key'), table_name='system_settings', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_system_settings_id'), table_name='system_settings', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_system_settings_group'), table_name='system_settings', schema='team_insight')
    op.drop_table('system_settings', schema='team_insight')
    # ### end Alembic commands ###