"""Add projects table

Revision ID: 60d3cd30879e
Revises: 758e6b2ba560
Create Date: 2025-06-25 15:04:12.157607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d3cd30879e'
down_revision: Union[str, None] = '758e6b2ba560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='team_insight'
    )
    op.create_index(op.f('ix_team_insight_permissions_id'), 'permissions', ['id'], unique=False, schema='team_insight')
    op.create_index(op.f('ix_team_insight_permissions_name'), 'permissions', ['name'], unique=True, schema='team_insight')
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='team_insight'
    )
    op.create_index(op.f('ix_team_insight_roles_id'), 'roles', ['id'], unique=False, schema='team_insight')
    op.create_index(op.f('ix_team_insight_roles_name'), 'roles', ['name'], unique=True, schema='team_insight')
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('backlog_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='team_insight'
    )
    op.create_index(op.f('ix_team_insight_users_backlog_id'), 'users', ['backlog_id'], unique=True, schema='team_insight')
    op.create_index(op.f('ix_team_insight_users_email'), 'users', ['email'], unique=True, schema='team_insight')
    op.create_index(op.f('ix_team_insight_users_id'), 'users', ['id'], unique=False, schema='team_insight')
    op.create_index(op.f('ix_team_insight_users_user_id'), 'users', ['user_id'], unique=True, schema='team_insight')
    op.create_table('oauth_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['team_insight.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='team_insight'
    )
    op.create_index(op.f('ix_team_insight_oauth_states_id'), 'oauth_states', ['id'], unique=False, schema='team_insight')
    op.create_index(op.f('ix_team_insight_oauth_states_state'), 'oauth_states', ['state'], unique=True, schema='team_insight')
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['team_insight.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='team_insight'
    )
    op.create_index(op.f('ix_team_insight_oauth_tokens_id'), 'oauth_tokens', ['id'], unique=False, schema='team_insight')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['team_insight.permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['team_insight.roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='team_insight'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['team_insight.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['team_insight.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'project_id', name='_user_role_project_uc'),
    schema='team_insight'
    )
    op.create_index(op.f('ix_team_insight_user_roles_id'), 'user_roles', ['id'], unique=False, schema='team_insight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_insight_user_roles_id'), table_name='user_roles', schema='team_insight')
    op.drop_table('user_roles', schema='team_insight')
    op.drop_table('role_permissions', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_oauth_tokens_id'), table_name='oauth_tokens', schema='team_insight')
    op.drop_table('oauth_tokens', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_oauth_states_state'), table_name='oauth_states', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_oauth_states_id'), table_name='oauth_states', schema='team_insight')
    op.drop_table('oauth_states', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_users_user_id'), table_name='users', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_users_id'), table_name='users', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_users_email'), table_name='users', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_users_backlog_id'), table_name='users', schema='team_insight')
    op.drop_table('users', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_roles_name'), table_name='roles', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_roles_id'), table_name='roles', schema='team_insight')
    op.drop_table('roles', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_permissions_name'), table_name='permissions', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_permissions_id'), table_name='permissions', schema='team_insight')
    op.drop_table('permissions', schema='team_insight')
    # ### end Alembic commands ###
