"""Add projects table

Revision ID: 60d3cd30879e
Revises: 758e6b2ba560
Create Date: 2025-06-25 15:04:12.157607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d3cd30879e'
down_revision: Union[str, None] = '758e6b2ba560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create projects table
    op.create_table('projects',
    sa.Column('backlog_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backlog_id'),
    sa.UniqueConstraint('project_key'),
    schema='team_insight'
    )
    op.create_index(op.f('ix_team_insight_projects_id'), 'projects', ['id'], unique=False, schema='team_insight')
    
    # Create project_members association table
    op.create_table('project_members',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['team_insight.projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['team_insight.users.id'], ),
    schema='team_insight'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_members', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_projects_id'), table_name='projects', schema='team_insight')
    op.drop_table('projects', schema='team_insight')
    # ### end Alembic commands ###
