"""Add project_members table

Revision ID: 78bde5c0eced
Revises: d0b3f6656e89
Create Date: 2025-06-25 15:19:48.532658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78bde5c0eced'
down_revision: Union[str, None] = 'd0b3f6656e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # project_members table is already created in 60d3cd30879e_add_projects_table
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # project_members table will be dropped by 60d3cd30879e_add_projects_table
    pass
    # ### end Alembic commands ###