"""create oauth_states table

Revision ID: 926f6717b64e
Revises: 
Create Date: 2025-06-12 16:08:14.103269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '926f6717b64e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    "oauth_states",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("state", sa.String(255), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("expires_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("id")
)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    "oauth_states",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("state", sa.String(255), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("expires_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("id")
)
    # ### end Alembic commands ###
