"""Add user preferences and settings

Revision ID: ab30ced40f83
Revises: 5c9c05c1b476
Create Date: 2025-07-03 03:54:52.412503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab30ced40f83'
down_revision: Union[str, None] = '5c9c05c1b476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns to users table
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=True, server_default='Asia/Tokyo'), schema='team_insight')
    op.add_column('users', sa.Column('locale', sa.String(length=10), nullable=True, server_default='ja'), schema='team_insight')
    op.add_column('users', sa.Column('date_format', sa.String(length=20), nullable=True, server_default='YYYY-MM-DD'), schema='team_insight')
    
    # Create user_preferences table
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('report_frequency', sa.String(length=20), nullable=True),
    sa.Column('notification_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['team_insight.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='team_insight'
    )
    op.create_index(op.f('ix_team_insight_user_preferences_id'), 'user_preferences', ['id'], unique=False, schema='team_insight')
    
    # Create login_history table
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('logout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['team_insight.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='team_insight'
    )
    op.create_index(op.f('ix_team_insight_login_history_id'), 'login_history', ['id'], unique=False, schema='team_insight')
    
    # Create activity_logs table
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['team_insight.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='team_insight'
    )
    op.create_index(op.f('ix_team_insight_activity_logs_id'), 'activity_logs', ['id'], unique=False, schema='team_insight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_insight_activity_logs_id'), table_name='activity_logs', schema='team_insight')
    op.drop_table('activity_logs', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_login_history_id'), table_name='login_history', schema='team_insight')
    op.drop_table('login_history', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_user_preferences_id'), table_name='user_preferences', schema='team_insight')
    op.drop_table('user_preferences', schema='team_insight')
    op.drop_column('users', 'date_format', schema='team_insight')
    op.drop_column('users', 'locale', schema='team_insight')
    op.drop_column('users', 'timezone', schema='team_insight')
    # ### end Alembic commands ###