"""Add RBAC tables and fix project relations

Revision ID: d0b3f6656e89
Revises: 60d3cd30879e
Create Date: 2025-06-25 15:16:11.075144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b3f6656e89'
down_revision: Union[str, None] = '60d3cd30879e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create RBAC tables only (skip existing tables)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='team_insight'
    )
    op.create_index(op.f('ix_team_insight_permissions_id'), 'permissions', ['id'], unique=False, schema='team_insight')
    op.create_index(op.f('ix_team_insight_permissions_name'), 'permissions', ['name'], unique=True, schema='team_insight')
    
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='team_insight'
    )
    op.create_index(op.f('ix_team_insight_roles_id'), 'roles', ['id'], unique=False, schema='team_insight')
    op.create_index(op.f('ix_team_insight_roles_name'), 'roles', ['name'], unique=True, schema='team_insight')
    
    # Create association tables
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['team_insight.permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['team_insight.roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='team_insight'
    )
    
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['team_insight.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['team_insight.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'project_id', name='_user_role_project_uc'),
    schema='team_insight'
    )
    op.create_index(op.f('ix_team_insight_user_roles_id'), 'user_roles', ['id'], unique=False, schema='team_insight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_insight_user_roles_id'), table_name='user_roles', schema='team_insight')
    op.drop_table('user_roles', schema='team_insight')
    op.drop_table('role_permissions', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_roles_name'), table_name='roles', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_roles_id'), table_name='roles', schema='team_insight')
    op.drop_table('roles', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_permissions_name'), table_name='permissions', schema='team_insight')
    op.drop_index(op.f('ix_team_insight_permissions_id'), table_name='permissions', schema='team_insight')
    op.drop_table('permissions', schema='team_insight')
    # ### end Alembic commands ###
