"""Add API key support to OAuth tokens

Revision ID: dee7fa186efe
Revises: 15fde8e78918
Create Date: 2025-06-27 05:44:32.605998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee7fa186efe'
down_revision: Union[str, None] = '15fde8e78918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to oauth_tokens table
    op.add_column('oauth_tokens', sa.Column('is_api_key', sa.Boolean(), nullable=True, default=False), schema='team_insight')
    op.add_column('oauth_tokens', sa.Column('backlog_space_key', sa.String(length=100), nullable=True), schema='team_insight')
    op.add_column('oauth_tokens', sa.Column('backlog_user_id', sa.String(length=100), nullable=True), schema='team_insight')
    op.add_column('oauth_tokens', sa.Column('backlog_user_email', sa.String(length=255), nullable=True), schema='team_insight')
    op.add_column('oauth_tokens', sa.Column('last_used_at', sa.DateTime(), nullable=True), schema='team_insight')
    
    # Set default value for existing rows
    op.execute("UPDATE team_insight.oauth_tokens SET is_api_key = false WHERE is_api_key IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_tokens', 'last_used_at', schema='team_insight')
    op.drop_column('oauth_tokens', 'backlog_user_email', schema='team_insight')
    op.drop_column('oauth_tokens', 'backlog_user_id', schema='team_insight')
    op.drop_column('oauth_tokens', 'backlog_space_key', schema='team_insight')
    op.drop_column('oauth_tokens', 'is_api_key', schema='team_insight')
    # ### end Alembic commands ###