"""Update projects table to match model

Revision ID: faba2f3bfca7
Revises: 78bde5c0eced
Create Date: 2025-06-25 15:20:40.359238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faba2f3bfca7'
down_revision: Union[str, None] = '78bde5c0eced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Projects table was already created with correct structure in 60d3cd30879e_add_projects_table
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No operations needed
    pass
    # ### end Alembic commands ###
